language: ruby
rvm:
  - 2.2.0
gemfile:
  - rails/Gemfile
before_install:
  - gem update --system
  - gem --version
before_script:
  - psql -c 'create database myhike_test;' -U postgres
script:
  - bundle exec rake -f rails/Rakefile db:migrate
  - bundle exec rspec
